server {
  listen 80;
  listen [::]:80;
  server_name example.com www.example.com reflector.example.com;

  root /dev/null;

  location ~ /.well-known/acme-challenge {
    allow all;
    root /var/www/acme-challenge;
  }

  location = /healthz {
    return 200 'ok';
    access_log off;
  }

  location / {
    return 308 https://$host$request_uri;
  }
}
