# If the Upgrade header is recieved, the header Connection is set to 'Upgrade', otherwise 'close'
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

  http2 on;
  server_name reflector.example.com;
  root /dev/null;
  access_log  /var/log/nginx/access.log actual_client;

  add_header_inherit merge;
  include /etc/nginx/conf.d/headers.inc;

  location ~ /\.ht {
    deny all;
  }
  location = /favicon.ico {
    log_not_found off;
    access_log off;
  }
  location = /robots.txt {
    log_not_found off;
    access_log off;
    allow all;
  }

  # allow uploads to /files
  location /files {
    alias /var/croquet-files/;

    dav_methods PUT;
    dav_access group:rw all:r;
    create_full_put_path on;
    client_max_body_size 100M;

    if ($request_method = OPTIONS) {
        add_header Access-Control-Allow-Methods "GET, PUT, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, Range" always;
        add_header Access-Control-Max-Age 1728000 always;
        return 204;
    }

    add_header Access-Control-Allow-Origin "*" always;
    add_header X-Robots-Tag "noindex";
}

  # proxy / to reflector image
  # (Docker Compose will create a network and DNS entry for the reflector service)
  location / {
    proxy_pass http://reflector:9090;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
#     proxy_read_timeout 120s;
#     proxy_send_timeout 120s;
    proxy_cache_bypass $http_upgrade;
#     proxy_buffering off;
#     proxy_cache off;
    include /etc/nginx/conf.d/proxy-directives.inc;
  }
}


