version: '3'

services:
  reflector:
    build:
      context: ./dist
      dockerfile: Dockerfile
    # image: reflector-standalone:20230524
    container_name: reflector
    environment:
      - CLUSTER_LABEL=$REFLECTOR_LABEL
    restart: unless-stopped
    networks:
      - croquet-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - $HOST_PORT:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - $WEB_ROOT_PATH:/var/croquet-in-a-box/web:ro
    depends_on:
      - reflector
    networks:
      - croquet-network

networks:
  croquet-network:
    driver: bridge