version: '3'

services:
  reflector:
    build:
      context: ./dist
      dockerfile: Dockerfile
    # image: reflector-standalone:20230524
    container_name: reflector
    environment:
      - CLUSTER_LABEL=$REFLECTOR_LABEL
    restart: unless-stopped
    networks:
      - croquet-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - $HOST_PORT:80
    volumes:
      - $WEB_ROOT_PATH:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
      - ./files:/usr/share/nginx/files
    depends_on:
      - reflector
    networks:
      - croquet-network

networks:
  croquet-network:
    driver: bridge