version: '3'

services:
  reflector:
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: reflector
    environment:
      - CLUSTER_LABEL=$REFLECTOR_LABEL
    restart: unless-stopped
    networks:
      - croquet-network

  fileserver:
    image: nginx:mainline-alpine
    container_name: fileserver
    restart: unless-stopped
    volumes:
      - ./nginx-fileserver.conf:/etc/nginx/nginx.conf:ro
    networks:
      - croquet-network
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - $HOST_PORT:80
    volumes:
      - ./nginx-webserver.conf:/etc/nginx/nginx.conf:ro
      - $WEB_ROOT_PATH:/var/croquet-in-a-box/web:ro
    depends_on:
      - reflector
      - fileserver
    networks:
      - croquet-network

networks:
  croquet-network:
    driver: bridge